<?php


return [
	['name' => 'Yety', 'price' => '240.00', 'image' => 'images/Road/road1.jpg', 'category' => 'road'],
	['name' => 'Chumba', 'price' => '679.00', 'image' => 'images/Road/road2.jpg', 'category' => 'road'],
	['name' => 'Avanti', 'price' => '249.00', 'image' => 'images/Road/road3.jpg', 'category' => 'road'],
	['name' => 'Batavus', 'price' => '349.00', 'image' => 'images/Road/road4.jpg', 'category' => 'road'],
	['name' => 'Bianchi', 'price' => '429.00', 'image' => 'images/Road/road5.jpg', 'category' => 'road'],
	['name' => 'Brunswick', 'price' => '799.00', 'image' => 'images/Road/road6.jpg', 'category' => 'road'],
	['name' => 'Orbea', 'price' => '789.00', 'image' => 'images/Road/road7.jpg', 'category' => 'road'],
	['name' => 'Caloi', 'price' => '1499.00', 'image' => 'images/Road/road8.jpg', 'category' => 'road'],
	['name' => 'Kross', 'price' => '499.00', 'image' => 'images/Road/road9.jpg', 'category' => 'road'],
	['name' => 'Coker', 'price' => '899.00', 'image' => 'images/Road/road10.jpg', 'category' => 'road'],
	['name' => 'Ross', 'price' => '1099.00', 'image' => 'images/Road/road11.jpg', 'category' => 'road'],
	['name' => 'Currys', 'price' => '1399.00', 'image' => 'images/Road/road12.jpg', 'category' => 'road'],
	['name' => 'Genesis', 'price' => '499.00', 'image' => 'images/Mountain/mountain1.jpg', 'category' => 'mountain'],
	['name' => 'Zara', 'price' => '159.00', 'image' => 'images/Mountain/mountain2.jpg', 'category' => 'mountain'],
	['name' => 'Whippet', 'price' => '549.00', 'image' => 'images/Mountain/mountain3.jpg', 'category' => 'mountain'],
	['name' => 'Rover', 'price' => '159.00', 'image' => 'images/Mountain/mountain4.jpg', 'category' => 'mountain'],
	['name' => 'Dahon', 'price' => '369.00', 'image' => 'images/Mountain/mountain5.jpg', 'category' => 'mountain'],
	['name' => 'Magna', 'price' => '149.00', 'image' => 'images/Mountain/mountain6.jpg', 'category' => 'mountain'],
	['name' => 'Vitus', 'price' => '449.00', 'image' => 'images/Mountain/mountain7.jpg', 'category' => 'mountain'],
	['name' => 'Dalon', 'price' => '379.00', 'image' => 'images/Mountain/mountain8.jpg', 'category' => 'mountain'],
	['name' => 'Atala', 'price' => '699.00', 'image' => 'images/Mountain/mountain9.jpg', 'category' => 'mountain'],
	['name' => 'Norman', 'price' => '739.00', 'image' => 'images/Mountain/mountain10.jpg', 'category' => 'mountain'],
	['name' => 'Dunelt', 'price' => '549.00', 'image' => 'images/Mountain/mountain11.jpg', 'category' => 'mountain'],
	['name' => 'Eddy', 'price' => '749.00', 'image' => 'images/Mountain/mountain12.jpg', 'category' => 'mountain'],
	['name' => 'Gendron', 'price' => '730.00', 'image' => 'images/Folding/folding1.jpg', 'category' => 'folding'],
	['name' => 'Gunnar', 'price' => '139.00', 'image' => 'images/Folding/folding2.jpg', 'category' => 'folding'],
	['name' => 'Haro', 'price' => '199.00', 'image' => 'images/Folding/folding3.jpg', 'category' => 'folding'],
	['name' => 'Harry', 'price' => '399.00', 'image' => 'images/Folding/folding4.jpg', 'category' => 'folding'],
	['name' => 'Bradbury', 'price' => '269.00', 'image' => 'images/Folding/folding5.jpg', 'category' => 'folding'],
	['name' => 'Hetchins', 'price' => '990.00', 'image' => 'images/Electric/electric1.jpg', 'category' => 'electric'],
	['name' => 'Derby', 'price' => '999.00', 'image' => 'images/Electric/electric2.jpg', 'category' => 'electric'],
	['name' => 'Hillman', 'price' => '1699.00', 'image' => 'images/Electric/electric3.jpg', 'category' => 'electric'],
	['name' => 'Huffy', 'price' => '1800.00', 'image' => 'images/Electric/electric4.jpg', 'category' => 'electric'],
	['name' => 'Ibis', 'price' => '990.00', 'image' => 'images/Electric/electric5.jpg', 'category' => 'electric'],
	['name' => 'Kona', 'price' => '170.00', 'image' => 'images/Electric/electric6.jpg', 'category' => 'electric'],
	['name' => 'Lotus', 'price' => '170.00', 'image' => 'images/Kids/kids1.jpg', 'category' => 'kids'],
	['name' => 'Matra', 'price' => '149.00', 'image' => 'images/Kids/kids2.jpg', 'category' => 'kids'],
	['name' => 'Moulton', 'price' => '109.00', 'image' => 'images/Kids/kids3.jpg', 'category' => 'kids'],
	['name' => 'Olmo', 'price' => '197.00', 'image' => 'images/Kids/kids4.jpg', 'category' => 'kids'],
	['name' => 'Pegas', 'price' => '109.00', 'image' => 'images/Kids/kids5.jpg', 'category' => 'kids'],
	['name' => 'Rans', 'price' => '102.00', 'image' => 'images/Kids/kids6.jpg', 'category' => 'kids'],
	['name' => 'Simson', 'price' => '129.00', 'image' => 'images/Kids/kids7.jpg', 'category' => 'kids'],
	['name' => 'Thomas', 'price' => '149.00', 'image' => 'images/Kids/kids8.jpg', 'category' => 'kids'],
	['name' => 'Urago', 'price' => '114.00', 'image' => 'images/Kids/kids9.jpg', 'category' => 'kids'],
	['name' => 'Whyte', 'price' => '99.00', 'image' => 'images/Kids/kids10.jpg', 'category' => 'kids'],
	['name' => 'Zigo', 'price' => '129.00', 'image' => 'images/Kids/kids11.jpg', 'category' => 'kids'],
	['name' => 'Kalkhoff', 'price' => '140.00', 'image' => 'images/Kids/kids12.jpg', 'category' => 'kids'],
];